theme: minima

include: 
  - assets/css/styles.css
  
title: ""

plugins:
  - jekyll-theme

nav_pages:
  - index.md
  - experience.md
  - projects.md

author:
    name: Zoe Ludena
    email: zoeludena@gmail.com

social_links:
  - title: "LinkedIn"
    icon: "linkedin"
    url: "https://www.linkedin.com/in/zoe-ludena/"
  - title: "GitHub"
    icon: "github"
    url: "https://github.com/zoeludena"
  - title: "Email"
    icon: "envelope"
    url: "mailto:zoeludena@gmail.com"
