theme: minima

social_links:
    - title: "LinkedIn"
      url: "https://www.linkedin.com/in/zoe-ludena/"
      icon: "linkedin"
    - title: "GitHub"
      url: "https://github.com/zoeludena"
      icon: "github"
    - title: "Email"
      url: "mailto:zoeludena@gmail.com"
      icon: "envelope"

include: 
  - assets/css/styles.css
  
title: ""

plugins:
  - jekyll-theme

header_pages:
  - index.md
  - experience.md
  - projects.md

author: Zoe Ludena
