title: "Zoe's Website"

theme: minima

author:
    name: Zoe Ludena
    email: zoeludena@gmail.com

include: 
  - assets/css/styles.css

description: >
  Welcome to my personal website! I'm Zoe Ludena, a passionate and data-driven professional with experience in environmental science, data analysis, and teaching. Here, you'll find an overview of my projects, my professional journey, and resources. Feel free to explore my experience, browse my latest projects, and get in touch!

plugins:
  - jekyll-theme

nav_pages:
  - index.md
  - experience.md
  - projects.md

social_links:
  - title: "LinkedIn"
    icon: "linkedin"
    url: "https://www.linkedin.com/in/zoe-ludena/"
  - title: "GitHub"
    icon: "github"
    url: "https://github.com/zoeludena"
  - title: "Email"
    icon: "envelope"
    url: "mailto:zoeludena@gmail.com"
